name:                lazy-foo
version:             0.1.0.0
github:              "ezoerner/lazy-foo"
license:             BSD3
author:              "Eric Zoerner"
maintainer:          "eric.zoerner@gmail.com"
copyright:           "Copyright: (c) 2018 Eric Zoerner"

extra-source-files:
- README.md
- ChangeLog.md

data-dir: assets

data-files:
- hello_world.bmp
- x.bmp
- press.bmp
- up.bmp
- down.bmp
- left.bmp
- right.bmp
- stretch.bmp
- loaded.png
- texture.png

ghc-options: -Wall -Werror -Wno-type-defaults

description:         Please see the README on Github at <https://github.com/ezoerner/lazy-foo#readme>

dependencies:
- base >= 4.7 && < 5
- linear
- sdl2
- text
- sdl2-image
- extra

library:
  source-dirs: src

executables:
  lesson01:
    main:                Lesson01.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson01
    dependencies:
    - lazy-foo

  lesson01p:
    main:                Lesson01Palf.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson01Palf
    dependencies:
    - lazy-foo

  lesson02:
    main:                Lesson02.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson02
    dependencies:
    - lazy-foo

  lesson02p:
    main:                Lesson02Palf.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson02Palf
    dependencies:
    - lazy-foo

  main:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - lazy-foo

  lesson03:
    main:                Lesson03.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson03
    dependencies:
    - lazy-foo

  lesson04:
    main:                Lesson04.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson04
    dependencies:
    - lazy-foo

  lesson05:
    main:                Lesson05.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson05
    dependencies:
    - lazy-foo

  lesson07:
    main:                Lesson07.hs
    source-dirs:         app
    ghc-options:
    - -threaded -rtsopts -with-rtsopts=-N -main-is Lesson07
    dependencies:
    - lazy-foo

tests:
  lazy-foo-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - lazy-foo
