name:                lazy-foo
version:             0.1.0.0
github:              "ezoerner/lazy-foo"
license:             BSD3
author:              "Eric Zoerner"
maintainer:          "eric.zoerner@gmail.com"
copyright:           "Copyright: (c) 2018 Eric Zoerner"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/ezoerner/lazy-foo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  lesson01:
    main:                Lesson01.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Lesson01
    dependencies:
    - lazy-foo
    - sdl2

tests:
  lazy-foo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazy-foo
